import Head from 'next/head'
import styles from 'styles/Projects.module.css'

export default function Projects() {
  return (
    <div>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1> Projects </h1>
		<p>
			Projects I have worked on.
		</p>
		<p className={styles.red}>
			Red	  
		</p>
      </main>
    </div>
  )
}

